name: LINT

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  black-lint:
    runs-on: ubuntu-latest
    name: black
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Install Black
        run: pip install black

      - name: Black linter
        uses: psf/black@stable
        with:
          options: "--check --verbose d20distribution test"

  pyright:
    runs-on: ubuntu-latest
    name: pyright
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: pyright
        uses: jakebailey/pyright-action@v2

  isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements-test.txt"